In [ ]:
import numpy as np
import pandas as pd
df=pd.read_csv("/content/diabetes.csv")
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [ ]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
df.tail()


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0

In [ ]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [ ]:
df.shape

(768, 9)

In [ ]:
df.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [ ]:
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [ ]:

x=df.iloc[:,:-1].values
x

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [ ]:
y=df.iloc[:,-1].values
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [ ]:
#splitting into training and testing data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=30,random_state=42)
x_train

array([[  0.   , 162.   ,  76.   , ...,  53.2  ,   0.759,  25.   ],
       [  4.   , 146.   ,  78.   , ...,  38.5  ,   0.52 ,  67.   ],
       [  4.   , 184.   ,  78.   , ...,  37.   ,   0.264,  31.   ],
       ...,
       [ 10.   , 101.   ,  86.   , ...,  45.6  ,   1.136,  38.   ],
       [  0.   , 141.   ,   0.   , ...,  42.4  ,   0.205,  29.   ],
       [  0.   , 125.   ,  96.   , ...,  22.5  ,   0.262,  21.   ]])

In [ ]:
x_test

array([[6.00e+00, 9.80e+01, 5.80e+01, 3.30e+01, 1.90e+02, 3.40e+01,
        4.30e-01, 4.30e+01],
       [2.00e+00, 1.12e+02, 7.50e+01, 3.20e+01, 0.00e+00, 3.57e+01,
        1.48e-01, 2.10e+01],
       [2.00e+00, 1.08e+02, 6.40e+01, 0.00e+00, 0.00e+00, 3.08e+01,
        1.58e-01, 2.10e+01],
       [8.00e+00, 1.07e+02, 8.00e+01, 0.00e+00, 0.00e+00, 2.46e+01,
        8.56e-01, 3.40e+01],
       [7.00e+00, 1.36e+02, 9.00e+01, 0.00e+00, 0.00e+00, 2.99e+01,
        2.10e-01, 5.00e+01],
       [6.00e+00, 1.03e+02, 7.20e+01, 3.20e+01, 1.90e+02, 3.77e+01,
        3.24e-01, 5.50e+01],
       [1.00e+00, 7.10e+01, 4.80e+01, 1.80e+01, 7.60e+01, 2.04e+01,
        3.23e-01, 2.20e+01],
       [0.00e+00, 1.17e+02, 0.00e+00, 0.00e+00, 0.00e+00, 3.38e+01,
        9.32e-01, 4.40e+01],
       [4.00e+00, 1.54e+02, 7.20e+01, 2.90e+01, 1.26e+02, 3.13e+01,
        3.38e-01, 3.70e+01],
       [5.00e+00, 1.47e+02, 7.80e+01, 0.00e+00, 0.00e+00, 3.37e+01,
        2.18e-01, 6.50e+01],
       [1.00e+01, 1.11e+02, 7.

In [ ]:
y_train

NameError: name 'y_train' is not defined

In [ ]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0])

In [ ]:
#normalisation
#standardScalar
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
ss.fit(x_train)
X_train_nor=ss.transform(x_train)
X_test_nor=ss.transform(x_test)
X_train_nor

array([[-1.13361128,  1.27782336,  0.35178129, ...,  2.66397899,
         0.84969947, -0.69448615],
       [ 0.05222164,  0.77835173,  0.45550266, ...,  0.81752952,
         0.1318716 ,  2.88487745],
       [ 0.05222164,  1.96459683,  0.45550266, ...,  0.62911631,
        -0.63701515, -0.18314849],
       ...,
       [ 1.83097102, -0.6264122 ,  0.87038815, ...,  1.70935206,
         1.98200535,  0.41341211],
       [-1.13361128,  0.62226685, -3.58963082, ...,  1.30740387,
        -0.81421952, -0.35359438],
       [-1.13361128,  0.12279523,  1.38899501, ..., -1.1922114 ,
        -0.64302208, -1.03537792]])

In [ ]:
X_test_nor

array([[ 6.45138099e-01, -7.20063126e-01, -5.81711052e-01,
         7.82447153e-01,  9.41036285e-01,  2.52289886e-01,
        -1.38440150e-01,  8.39526822e-01],
       [-5.40694821e-01, -2.83025458e-01,  2.99920605e-01,
         7.19973281e-01, -6.91610031e-01,  4.65824859e-01,
        -9.85416965e-01, -1.03537792e+00],
       [-5.40694821e-01, -4.07893363e-01, -2.70546938e-01,
        -1.27919062e+00, -6.91610031e-01, -1.49658299e-01,
        -9.55382326e-01, -1.03537792e+00],
       [ 1.23805456e+00, -4.39110340e-01,  5.59224034e-01,
        -1.27919062e+00, -6.91610031e-01, -9.28432907e-01,
         1.14103546e+00,  7.25203362e-02],
       [ 9.41596329e-01,  4.66181972e-01,  1.07783089e+00,
        -1.27919062e+00, -6.91610031e-01, -2.62706226e-01,
        -7.99202204e-01,  1.43608742e+00],
       [ 6.45138099e-01, -5.63978245e-01,  1.44338548e-01,
         7.19973281e-01,  9.41036285e-01,  7.17042474e-01,
        -4.56807322e-01,  1.86220214e+00],
       [-8.37153051e-01, -1.562921

In [ ]:
#model creation
from sklearn.neighbors import KNeighborsClassifier
knn1=KNeighborsClassifier(n_neighbors=7)
knn1.fit(X_train_nor,y_train)
y_pred=knn1.predict(X_test_nor)
y_pred


array([0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0])

In [ ]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0])

In [ ]:
#performsance evaluation
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.65      0.79      0.71        19
           1       0.43      0.27      0.33        11

    accuracy                           0.60        30
   macro avg       0.54      0.53      0.52        30
weighted avg       0.57      0.60      0.57        30



In [ ]:
#accuracy
from sklearn.metrics import accuracy_score
accuracy_score(y_pred,y_test)

0.6

In [ ]:
pred=knn1.predict(ss.transform([[6,148,72,35,0,33.6,0.627,50,]]))
pred

array([1])